apiVersion: apps/v1
kind: Deployment
metadata: 
  name: static-site
  labels:
    app: static-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: nginx
        image: localhost:32000/my-static-site:v1.0.1
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  selector:
    app: static-site
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31234
  type: NodePort
