apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate ConfigMap from External file
configMapGenerator:
  - name: static-site-content
    files:
      - index.html # This reads index.html from disk

# Deployment
resources:
  - deployment.yaml # Uses the generated ConfigMap
